CUSTOMERS = {

    "CUST1001": {
        "customer_id": "CUST1001",
        "name": "John Smith",
        "gender": "Male",
        "age": 45,
        "tenure_months": 6,
        "monthly_charges": 90,
        "total_charges": 540,
        "internet_service": "Fiber",
        "phone_service": "Yes",
        "contract_type": "Month-to-Month",
        "payment_method": "Electronic Check",
        "avg_monthly_gb_used": 80,
        "avg_monthly_minutes": 150,
        "num_support_tickets": 5,
        "satisfaction_score": 2,
        "num_additional_services": 1
    },

    "CUST1002": {
        "customer_id": "CUST1002",
        "name": "Emily Davis",
        "gender": "Female",
        "age": 31,
        "tenure_months": 2,
        "monthly_charges": 120,
        "total_charges": 240,
        "internet_service": "Fiber",
        "phone_service": "Yes",
        "contract_type": "Month-to-Month",
        "payment_method": "Electronic Check",
        "avg_monthly_gb_used": 95,
        "avg_monthly_minutes": 90,
        "num_support_tickets": 8,
        "satisfaction_score": 1,
        "num_additional_services": 0
    },

    "CUST1003": {
        "customer_id": "CUST1003",
        "name": "Michael Brown",
        "gender": "Male",
        "age": 54,
        "tenure_months": 72,
        "monthly_charges": 55,
        "total_charges": 3960,
        "internet_service": "DSL",
        "phone_service": "Yes",
        "contract_type": "Two-Year",
        "payment_method": "Bank Transfer",
        "avg_monthly_gb_used": 35,
        "avg_monthly_minutes": 520,
        "num_support_tickets": 0,
        "satisfaction_score": 5,
        "num_additional_services": 4
    },

    "CUST1004": {
        "customer_id": "CUST1004",
        "name": "Sophia Wilson",
        "gender": "Female",
        "age": 39,
        "tenure_months": 24,
        "monthly_charges": 105,
        "total_charges": 2520,
        "internet_service": "Fiber",
        "phone_service": "Yes",
        "contract_type": "One-Year",
        "payment_method": "Credit Card",
        "avg_monthly_gb_used": 110,
        "avg_monthly_minutes": 310,
        "num_support_tickets": 3,
        "satisfaction_score": 3,
        "num_additional_services": 2
    },

    "CUST1005": {
        "customer_id": "CUST1005",
        "name": "David Miller",
        "gender": "Male",
        "age": 28,
        "tenure_months": 4,
        "monthly_charges": 135,
        "total_charges": 540,
        "internet_service": "Fiber",
        "phone_service": "Yes",
        "contract_type": "Month-to-Month",
        "payment_method": "Electronic Check",
        "avg_monthly_gb_used": 118,
        "avg_monthly_minutes": 120,
        "num_support_tickets": 10,
        "satisfaction_score": 1,
        "num_additional_services": 0
    },

    "CUST1006": {
        "customer_id": "CUST1006",
        "name": "Olivia Taylor",
        "gender": "Female",
        "age": 47,
        "tenure_months": 60,
        "monthly_charges": 75,
        "total_charges": 4500,
        "internet_service": "Cable",
        "phone_service": "Yes",
        "contract_type": "Two-Year",
        "payment_method": "Credit Card",
        "avg_monthly_gb_used": 55,
        "avg_monthly_minutes": 420,
        "num_support_tickets": 1,
        "satisfaction_score": 5,
        "num_additional_services": 5
    },

    "CUST1007": {
        "customer_id": "CUST1007",
        "name": "James Anderson",
        "gender": "Male",
        "age": 36,
        "tenure_months": 12,
        "monthly_charges": 82,
        "total_charges": 984,
        "internet_service": "DSL",
        "phone_service": "No",
        "contract_type": "One-Year",
        "payment_method": "Bank Transfer",
        "avg_monthly_gb_used": 48,
        "avg_monthly_minutes": 250,
        "num_support_tickets": 2,
        "satisfaction_score": 4,
        "num_additional_services": 3
    },

    "CUST1008": {
        "customer_id": "CUST1008",
        "name": "Emma Thomas",
        "gender": "Female",
        "age": 25,
        "tenure_months": 1,
        "monthly_charges": 140,
        "total_charges": 140,
        "internet_service": "Fiber",
        "phone_service": "Yes",
        "contract_type": "Month-to-Month",
        "payment_method": "Electronic Check",
        "avg_monthly_gb_used": 115,
        "avg_monthly_minutes": 80,
        "num_support_tickets": 7,
        "satisfaction_score": 1,
        "num_additional_services": 0
    }
}